databases:
  - name: ZeMusic
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: ZeMusic
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m ZeMusic
    region: frankfurt
    envVars:
      - key: MONGO_DB_URI
        sync: false
      - key: API_HASH 
        sync: false
      - key: APP_ID 
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: LOGGER_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: DATABASE_URL
        fromDatabase:
          name: ZeMusic
          property: connectionString   
    autoDeploy: false
